# Josue Rivas Muñoz 2021-01-05
# Revisión 1.1
version: '3.8'

services:
  keycloak:
    container_name: keycloak15_v2
    image: jboss/keycloak:15.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgrespr
      DB_PORT: 5432
      DB_DATABASE: dbapp
      DB_SCHEMA: db_keycloak
      DB_USER: postgres
      DB_PASSWORD: pass
      JDBC_URL: jdbc:postgresql://database-test-1.c1wjwjzwhjhe.us-east-2.rds.amazonaws.com:5432/dbapp   #  # Para este ejemplo se está conectando a una bd en aws
    ports:
      - '9090:8080'
    networks:
      - keycloak-network
    restart: unless-stopped
    volumes:
      - './cli/databases/postgres/:/opt/jboss/tools/cli/databases/postgres/'

networks:
  keycloak-network:
    external: true
    
#volumes:
#  jboss-data:
#    driver: local
