# Josue Rivas Muñoz 2021-01-05
# Revisión 1.1
version: '3.8'

services:
  keycloak:
    container_name: jokeycloak15V5
    image: jboss/keycloak:15.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgrespr
      DB_PORT: 5432
      DB_DATABASE: dbapp
      DB_SCHEMA: db_keycloak
      DB_USER: postgres
      DB_PASSWORD: Perro0Bejero92
      JDBC_URL: jdbc:postgresql://database-test-1.c1wjwjzwhjhe.us-east-2.rds.amazonaws.com:5432/dbapp   # jdbc:postgresql://postgrespr/keycloak
    ports:
      - '9090:8080'
    networks:
      - keycloak-network
    restart: unless-stopped


networks:
  keycloak-network:
    external: true
    
#volumes:
#  jboss-data:
#    driver: local
