# Josue Rivas Mu침oz 2021-01-05
# Revisi칩n 1.1
version: '3.8'

services:
  keycloak:
    container_name: keycloak15_v1
    image: jotacr/keycloak15:0.1.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres # Este no ser치 concatenado ya que se cambia por medio del llamado del JDBC_URL, pero la variable es requerida para levantar el contenedor
      DB_PORT: 5432
      DB_DATABASE: dbapp
      DB_SCHEMA: db_keycloak
      DB_USER: postgres
      DB_PASSWORD: pass
      JDBC_URL: jdbc:postgresql://database-test-1.c1wjwjzwhjhe.us-east-2.rds.amazonaws.com:5432/dbapp   # Para este ejemplo se est치 conectando a una bd en aws

    ports:
      - '9090:8080'
    networks:
      - keycloak-network
    restart: unless-stopped


networks:
  keycloak-network:
    external: true
    
#volumes:
#  jboss-data:
#    driver: local
